### ISSUE TITLE
Can't load archetypes

### ISSUE THREAD

**Issue by wolandscat** [openEHR/adl-designer#10]
When I hit the Load button, nothing happens. Again; then I am asked to re-authenticate to Github (this was after doing nothing for 30 mins on the Designer tab in Chrome); then this:

![image](https://cloud.githubusercontent.com/assets/1481744/11422724/42e94aaa-9436-11e5-8b7f-7029b899e789.png)

Doing a refresh on the URI does nothing. If I kill the tab in Chrome and start again, I get to a sensible point but when I hit the Load button now, I get this:

![image](https://cloud.githubusercontent.com/assets/1481744/11422778/92415598-9436-11e5-9171-ef2ca6bc4b7b.png)

It offers only 'Template', which is empty. I can't see to see any archetypes to load (but they are there in my fork of the EhrScape demo repo, that part worked).

**Comment by markopi64** [comment]
At the time I was just deploying new version of the application, that's why you got that error.

Logging in the application shows you just the template designer. We haven't yet decided how to incorporate archetype and template designer into a single page.

This is why load button only lets you load templates, and there are none in the predefined repository. If you create a new template and try to fill a slot, you should see the list of archetypes matching that slot.

**Comment by borutf** [comment]
Archetype editor has been updated with github support.
